### ISSUE TITLE
Chaining I-Impute (C-Impute?) with another imputation tool

### ISSUE THREAD

**Issue by cnk113** [xikanfeng2/I-Impute#1]
Hello,

I'm trying to combined another existing imputation tool with I-Impute, but I was confused if I should be using the same I-Impute function right after imputation with a different tool?

Thanks

**Comment by xikanfeng2** [comment]
Yes, you can just pass the outputs of other imputation tools to the function of I-Impute. If you set the iteration=False, I-Impute just runs C-Impute once. If iteration=True, I-Impute will iteratively run C-Impute to achieve a consistent result.
